### ISSUE TITLE
Global CSS normalize and shared styles

### ISSUE THREAD

**Issue by evanfuture** [hlxsites/vg-macktrucks-com#10]
It will be important for long-term development to have a browser-css-normalizer applied, such as https://github.com/necolas/normalize.css/blob/master/normalize.css in order to avoid edge-case css in browsers.

Also should add 
```css
/* Preferred box-sizing value */
*,
*::before,
*::after {
    box-sizing: border-box;
}
```

And have a clearly defined place in the global css file for shared custom property definitions and other global styles for this site.
